[package]
name = "orb-isp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
image = "0.25.2"
inferno = "0.11.21"
libc = "0.2.159"
rand = { version = "0.8.5", features = ["min_const_gen"] }
rodio = "0.19.0"
tracing = "0.1"
tracing-flame = "0.2.0"
tracing-subscriber = { version = "0.3", features = ["local-time"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"]}

[[bench]]
name = "convolution"
harness = false

[[bench]]
name = "isp"
harness = false
