[package]
name = "orb-http-client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
opentelemetry = { version = "0.21", features = ["trace"] }
tracing = "0.1.40"
tracing-opentelemetry = "0.22"
color-eyre = { workspace = true }
orb-telemetry = { workspace = true }
orb-security-utils = { workspace = true, features = ["reqwest"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.22.1"
hyper = "1.4.1"

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
