[package]
name = "orb-telemetry"
version = "0.0.0"
description = "Standardized telemetry setup for the orb"
authors = ["Ryan Butler <thebutlah@users.noreply.github.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tracing-journald.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[target.'cfg(tokio_unstable)'.dependencies]
console-subscriber.workspace = true

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = ['cfg(tokio_unstable)']

[dev-dependencies]
color-eyre.workspace = true
opentelemetry = { version = "0.27.1" }
opentelemetry-otlp = { version = "0.27.0" }
opentelemetry-datadog = { version =  "0.15.0", features = ["reqwest-client"] }
opentelemetry-stdout = { version = "0.27.0", features = ["trace"] }
opentelemetry_sdk = { version = "0.27.1", features = ["rt-tokio"] }
reqwest.workspace = true
tokio.workspace = true
tracing-opentelemetry = "0.28.0"
