[package]
name = "orb-telemetry"
version = "0.0.0"
description = "Standardized telemetry setup for the orb"
authors = ["Ryan Butler <thebutlah@users.noreply.github.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tracing-journald.workspace = true
opentelemetry = { version = "0.21", features = ["trace"] }
opentelemetry-otlp = { version = "0.14", features = ["trace", "tonic"] }
opentelemetry_sdk = { version = "0.21", features = ["trace", "rt-tokio"] }
opentelemetry-datadog = "0.10"
tracing-opentelemetry = "0.22"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json", "time"] }
tracing = "0.1.40"
thiserror = "1.0.65"


[target.'cfg(tokio_unstable)'.dependencies]
console-subscriber.workspace = true

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = ['cfg(tokio_unstable)']
